# Set default editor in all shells

# Try to load the ~/.local/.dotfiles/editor.env.sh generated by dot.yaml install
if [ -f ~/.local/.dotfiles/editor.env.sh ]; then
  source ~/.local/.dotfiles/editor.env.sh
fi

# fallback and convert space-separated string to array
editor_arr=(${__dotfiles_editor_opts:-nvim vim nano vi})
visual_arr=(${__dotfiles_visual_opts:-nvim vim nano vi})

# Find first available editor and set EDITOR
for editor in "${editor_arr[@]}"; do
  if command -v "$editor" >/dev/null 2>&1; then
    export EDITOR="$editor"
    break
  fi
done

# Find first available visual editor and set VISUAL
for visual in "${visual_arr[@]}"; do
  if command -v "$visual" >/dev/null 2>&1; then
    export VISUAL="$visual"
    break
  fi
done
