#!/bin/bash

# Set default editor in all shells
# shellcheck disable=SC2155

# Try to load the ~/.local/.dotfiles/editor.env.sh generated by dot.yaml install
if [[ -f ~/.local/.dotfiles/editor.env.sh ]]; then
	# shellcheck source=/dev/null
	source ~/.local/.dotfiles/editor.env.sh
fi

# Set default editors if not set
: "${__dotfiles_editor_opts:=nvim vim nano vi}"
: "${__dotfiles_visual_opts:=nvim vim nano vi}"

# Function to find first available command from a list of options
find_first_available_cmd() {
	local options="$1"
	local cmd

	# Split options into lines and process each one
	options_list=$(echo "${options}" | tr ' ' '\n')
	while read -r cmd; do
		if command -v "${cmd}" >/dev/null 2>&1; then
			echo "${cmd}"
			return 0
		fi
	done <<<"${options_list}"
	return 1
}

# Set EDITOR and VISUAL to first available editor
export EDITOR=$(find_first_available_cmd "${__dotfiles_editor_opts}")
export VISUAL=$(find_first_available_cmd "${__dotfiles_visual_opts}")
