# Set default editor in Fish shell

# Try to load the ~/.local/.dotfiles/editor.env.sh generated by dot.yaml install
if test -f ~/.local/.dotfiles/editor.env.sh
    source ~/.local/.dotfiles/editor.env.sh
end

# fallback - respect any existing values or use defaults
set -q __dotfiles_editor_opts; or set -gx __dotfiles_editor_opts "nvim vim nano vi"
set -q __dotfiles_visual_opts; or set -gx __dotfiles_visual_opts "nvim vim nano vi"

# Convert space-separated strings to arrays
set editor_arr (string split " " $__dotfiles_editor_opts)
set visual_arr (string split " " $__dotfiles_visual_opts)

# Find first available editor
for editor in $editor_arr
    if command -v $editor >/dev/null 2>&1
        set -gx EDITOR $editor
        break
    end
end

# Find first available visual editor
for visual in $visual_arr
    if command -v $visual >/dev/null 2>&1
        set -gx VISUAL $visual
        break
    end
end
