#!/usr/bin/env bash
#
# create_shell_stub_test.sh - Test script for create_shell_stub utility
#
# This script runs a series of tests against the create_shell_stub utility
# to verify that it correctly creates and updates shell configuration files
# with tagged content blocks.
#
# Usage:
#   ./test/create_shell_stub_test.sh [OPTIONS]
#
# Options:
#   --keep-logs    Keep test logs after running (useful for debugging)
#
# Test Coverage:
#   - Creating new files with default and custom tags
#   - Updating existing files
#   - Preserving content outside of tagged blocks
#   - Creating nested directories
#   - Handling multiline content
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
RESET='\033[0m'

# Test directory
TEST_DIR="$(mktemp -d)"
LOG_DIR="${TEST_DIR}/logs"
mkdir -p "${LOG_DIR}"
BIN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../bin" && pwd)"
SCRIPT_PATH="${BIN_DIR}/create_shell_stub"

# Test result counters
TESTS_TOTAL=0
TESTS_PASSED=0
TESTS_FAILED=0

# Logging utilities
log() {
	local level="$1"
	local message="$2"
	local color=""

	case "${level}" in
	info) color="${BLUE}" ;;
	success) color="${GREEN}" ;;
	warning) color="${YELLOW}" ;;
	error) color="${RED}" ;;
	*) color="${RESET}" ;;
	esac

	printf "${color}${BOLD}[TEST]${RESET} ${color}%s${RESET}\n" "${message}"
}

# Test utilities
run_test() {
	local test_name="$1"
	local test_func="$2"
	local log_file="${LOG_DIR}/${test_name// /_}.log"

	log "info" "Running test: ${test_name}"
	TESTS_TOTAL=$((TESTS_TOTAL + 1))

	# Run the test function and redirect script output to log file
	if ${test_func} >"${log_file}" 2>&1; then
		log "success" "Test passed: ${test_name}"
		TESTS_PASSED=$((TESTS_PASSED + 1))
	else
		log "error" "Test failed: ${test_name}"
		log "info" "Log file: ${log_file}"
		log "info" "Last 5 lines of log:"
		# shellcheck disable=SC2312
		tail -n 5 "${log_file}" | sed 's/^/    /'
		TESTS_FAILED=$((TESTS_FAILED + 1))
	fi

	echo
}

assert_file_contains() {
	local file="$1"
	local content="$2"

	if grep -q "${content}" "${file}"; then
		return 0
	else
		log "error" "Expected file to contain: '${content}'"
		log "error" "Actual file content:"
		cat "${file}" >&2
		return 1
	fi
}

assert_file_matches() {
	local file="$1"
	local expected="$2"

	if diff -q "${file}" "${expected}" >/dev/null; then
		return 0
	else
		log "error" "Files don't match:"
		diff "${file}" "${expected}" >&2
		return 1
	fi
}

# Setup and teardown
setup() {
	log "info" "Setting up test environment in ${TEST_DIR}"
	mkdir -p "${TEST_DIR}"
	chmod +x "${SCRIPT_PATH}"
}

teardown() {
	log "info" "Cleaning up test environment"
	if [[ ${KEEP_LOGS} != "true" ]]; then
		rm -rf "${TEST_DIR}"
	else
		log "info" "Logs kept at ${LOG_DIR}"
	fi
}

# Test cases
test_create_new_file_default_tag() {
	local target="${TEST_DIR}/new_file_default.sh"

	echo "# Test content" | "${SCRIPT_PATH}" "${target}"

	assert_file_contains "${target}" "## <autogenerated-dotfiles-block>"
	assert_file_contains "${target}" "# Test content"
	assert_file_contains "${target}" "## </autogenerated-dotfiles-block>"
}

test_create_new_file_custom_tag() {
	local target="${TEST_DIR}/new_file_custom.sh"

	echo "# Test content with custom tag" | "${SCRIPT_PATH}" "${target}" --block-tag=custom-tag

	assert_file_contains "${target}" "## <custom-tag>"
	assert_file_contains "${target}" "# Test content with custom tag"
	assert_file_contains "${target}" "## </custom-tag>"
}

test_update_existing_file() {
	local target="${TEST_DIR}/update_file.sh"

	# First create the file
	echo "# Initial content" | "${SCRIPT_PATH}" "${target}"

	# Then update it
	echo "# Updated content" | "${SCRIPT_PATH}" "${target}"

	# Verify content was updated
	assert_file_contains "${target}" "## <autogenerated-dotfiles-block>"
	assert_file_contains "${target}" "# Updated content"
	assert_file_contains "${target}" "## </autogenerated-dotfiles-block>"

	# Verify old content was replaced
	if grep -q "# Initial content" "${target}"; then
		log "error" "File should not contain initial content"
		cat "${target}" >&2
		return 1
	fi

	return 0
}

test_preserve_surrounding_content() {
	local target="${TEST_DIR}/surrounding.sh"

	# Create file with content before and after the block
	cat >"${target}" <<'EOF'
# Content before block

## <autogenerated-dotfiles-block>
# Initial block content
## </autogenerated-dotfiles-block>

# Content after block
EOF

	# Update the block
	echo "# Updated block content" | "${SCRIPT_PATH}" "${target}"

	# Verify all parts are preserved correctly
	assert_file_contains "${target}" "# Content before block"
	assert_file_contains "${target}" "## <autogenerated-dotfiles-block>"
	assert_file_contains "${target}" "# Updated block content"
	assert_file_contains "${target}" "## </autogenerated-dotfiles-block>"
	assert_file_contains "${target}" "# Content after block"

	# Create expected file to verify exact content
	local expected="${TEST_DIR}/expected_surrounding.sh"
	cat >"${expected}" <<'EOF'
# Content before block

## <autogenerated-dotfiles-block>
# Updated block content
## </autogenerated-dotfiles-block>

# Content after block
EOF

	assert_file_matches "${target}" "${expected}"
}

test_custom_tag_update() {
	local target="${TEST_DIR}/custom_tag_update.sh"

	# Create file with custom tag
	echo "# Initial custom tag content" | "${SCRIPT_PATH}" "${target}" --block-tag=my-tag

	# Update with same custom tag
	echo "# Updated custom tag content" | "${SCRIPT_PATH}" "${target}" --block-tag=my-tag

	# Verify content was updated
	assert_file_contains "${target}" "## <my-tag>"
	assert_file_contains "${target}" "# Updated custom tag content"
	assert_file_contains "${target}" "## </my-tag>"

	# Verify old content was replaced
	if grep -q "# Initial custom tag content" "${target}"; then
		log "error" "File should not contain initial content"
		cat "${target}"
		return 1
	fi

	return 0
}

test_create_nested_directories() {
	local target="${TEST_DIR}/nested/dirs/file.sh"

	log "info" "Creating file in nested directory: ${target}"
	# Create parent directory manually to avoid quoting issues
	mkdir -p "$(dirname "${target}")"

	# This should create the file
	echo "# Content in nested dirs" | "${SCRIPT_PATH}" "${target}"

	# Check that directories were created
	if [[ ! -d "$(dirname "${target}")" ]]; then
		log "error" "Nested directories were not created"
		ls -la "${TEST_DIR}" >&2
		return 1
	fi

	# Check file content
	if [[ ! -f ${target} ]]; then
		log "error" "Target file was not created"
		ls -la "$(dirname "${target}")" >&2
		return 1
	fi

	log "info" "File created successfully, checking content"
	assert_file_contains "${target}" "## <autogenerated-dotfiles-block>"
	assert_file_contains "${target}" "# Content in nested dirs"
	assert_file_contains "${target}" "## </autogenerated-dotfiles-block>"

	return 0
}

test_multiline_content() {
	local target="${TEST_DIR}/multiline.sh"

	# Create file with multiline content
	"${SCRIPT_PATH}" "${target}" <<'EOF'
# This is a multiline
# content block with
export VAR="value"
source "$HOME/some/path"
# multiple lines
EOF

	# Verify all lines are present
	assert_file_contains "${target}" "# This is a multiline"
	assert_file_contains "${target}" "# content block with"
	assert_file_contains "${target}" 'export VAR="value"'
	# shellcheck disable=SC2016
	assert_file_contains "${target}" 'source "$HOME/some/path"'
	assert_file_contains "${target}" "# multiple lines"

	return 0
}

# Run all tests
# Main execution
main() {
	# Handle command line arguments
	KEEP_LOGS=false
	for arg in "$@"; do
		case ${arg} in
		--keep-logs)
			KEEP_LOGS=true
			;;
		*)
			log "error" "Unknown option: ${arg}"
			;;
		esac
	done

	setup

	log "info" "Environment info:"
	log "info" "Test directory: ${TEST_DIR}"
	log "info" "Log directory: ${LOG_DIR}"
	log "info" "Script path: ${SCRIPT_PATH}"

	run_test "Create new file with default tag" test_create_new_file_default_tag
	run_test "Create new file with custom tag" test_create_new_file_custom_tag
	run_test "Update existing file" test_update_existing_file
	run_test "Preserve surrounding content" test_preserve_surrounding_content
	run_test "Update with custom tag" test_custom_tag_update
	run_test "Create nested directories" test_create_nested_directories
	run_test "Handle multiline content" test_multiline_content

	# Print summary
	echo "=========================================="
	echo "Test Summary:"
	echo "Total: ${TESTS_TOTAL}"
	echo -e "${GREEN}Passed: ${TESTS_PASSED}${RESET}"
	if [[ ${TESTS_FAILED} -gt 0 ]]; then
		echo -e "${RED}Failed: ${TESTS_FAILED}${RESET}"
	else
		echo -e "${GREEN}Failed: ${TESTS_FAILED}${RESET}"
	fi
	echo "=========================================="

	teardown

	# Return success only if all tests passed
	[[ ${TESTS_FAILED} -eq 0 ]]
}

# Run tests
main "$@"
