# Prettier friendly markdownlint config (all formatting rules disabled)
extends: markdownlint/style/prettier

# Rules
#########

# MD040 (Fenced code blocks should have a language specified)
MD040: false
