# Rotz default configurations

dotfiles: ~/.dotfiles

variables:
  shell:
    # Set up editor preferences based on availability, fallback to "nvim vim nano vi" by default
    ## (string) Order to set $EDITOR env
    EDITOR: nvim vim nano vi
    ## (string) Order to set $VISUAL env
    VISUAL: cursor code zed nvim vim nano vi
