#!/usr/bin/env bash

# Generates .mise.toml per gitdir with GH_TOKEN routing per git account.
# Reads account config from $DOTFILES_DIR/local/gitconfig.json (generated by git-op-config).

set -euo pipefail

### Config

dotfiles_local_dir="${DOTFILES_DIR:-$HOME/.dotfiles}/local"
gitconfig_json_path="$dotfiles_local_dir/gitconfig.json"

debug_mode="${DEBUG:-false}"
force_mode=false

for arg in "$@"; do
  case "$arg" in
    --force) force_mode=true ;;
  esac
done

### Helpers

log() {
  local level="$1"
  local msg="$2"
  [[ "$level" == "debug" && "$debug_mode" != "true" ]] && return
  echo "$level: $msg"
}

expand_tilde() {
  echo "${1/#\~/$HOME}"
}

### Setup

generate_mise_toml() {
  local gitdir="$1"
  local gh_user="$2"
  local real_gitdir
  real_gitdir="$(expand_tilde "$gitdir")"
  local mise_toml="$real_gitdir/.mise.toml"

  mkdir -p "$real_gitdir"

  if [[ -f "$mise_toml" ]]; then
    if grep -q "GH_TOKEN" "$mise_toml"; then
      if [[ "$force_mode" == "true" ]]; then
        log warn "Overwriting existing GH_TOKEN in $mise_toml"
        # Remove existing [env] block with GH_TOKEN to re-add cleanly
        # This is a simple sed approach — only removes the GH_TOKEN line
        sed -i '' '/^GH_TOKEN/d' "$mise_toml"
      else
        log warn "GH_TOKEN already set in $mise_toml — skipping (use --force to overwrite)"
        return
      fi
    fi
    log info "Appending GH_TOKEN to existing $mise_toml"
    # Append to existing [env] section if present, otherwise add the section
    if grep -q '^\[env\]' "$mise_toml"; then
      sed -i '' '/^\[env\]/a\
GH_TOKEN = "{{ exec(command='"'"'gh auth token --user '"$gh_user"''"'"') }}"
' "$mise_toml"
    else
      printf '\n[env]\nGH_TOKEN = "{{ exec(command='"'"'gh auth token --user %s'"'"') }}"\n' "$gh_user" >> "$mise_toml"
    fi
  else
    log info "Creating $mise_toml for gh_user=$gh_user"
    cat > "$mise_toml" << EOF
[env]
GH_TOKEN = "{{ exec(command='gh auth token --user $gh_user') }}"
EOF
  fi
}

### Prerequisites

if ! command -v jq &>/dev/null; then
  echo "Error: jq is not installed. Install it with 'brew install jq'"
  exit 1
fi

if [[ ! -f "$gitconfig_json_path" ]]; then
  echo "Error: $gitconfig_json_path not found. Run 'rotz install tools/git/git-op-config' first."
  exit 1
fi

### Execute

log info "Reading $gitconfig_json_path..."
gitconfig_data="$(jq -c '.' "$gitconfig_json_path")"

account_count="$(echo "$gitconfig_data" | jq '.accounts | length')"

for i in $(seq 0 $((account_count - 1))); do
  account="$(echo "$gitconfig_data" | jq -c ".accounts[$i]")"
  account_name="$(echo "$account" | jq -r '.name')"
  gh_user="$(echo "$account" | jq -r '.gh_user // empty')"

  if [[ -z "$gh_user" ]]; then
    log warn "Account '$account_name' has no gh_user — skipping mise setup"
    continue
  fi

  log info "Configuring mise for account: $account_name (gh_user=$gh_user)"

  gitdir_count="$(echo "$account" | jq '.gitdirs | length')"
  for j in $(seq 0 $((gitdir_count - 1))); do
    gitdir="$(echo "$account" | jq -r ".gitdirs[$j]")"
    log info "  → $gitdir"
    generate_mise_toml "$gitdir" "$gh_user"
  done
done

log info "Done."
