#!/usr/bin/env fish

# Set DOTFILES_DIR if not already set
set -q DOTFILES_DIR; or set -g DOTFILES_DIR "$HOME/.dotfiles"

function install_dotfiles_conf
    set -q XDG_CONFIG_HOME; or set -g XDG_CONFIG_HOME "$HOME/.config"
    set -g CONFIG_PATH "$XDG_CONFIG_HOME"
    set -g FISH_CONFIG "$CONFIG_PATH/fish"

    # # Ensure the conf.d directory exists
    # mkdir -p "$FISH_CONFIG/conf.d"

    # Create dotfiles.fish in conf.d
    set DOTFILES_CONF "$FISH_CONFIG/conf.d/zzz_dotfiles.fish"

    echo "\
      # DO NOT EDIT THIS FILE
      # It is automatically generated by dotfiles install script
      #
      # Load dotfiles config
      set -gx DOTFILES_DIR \"$DOTFILES_DIR\"
      source \"$DOTFILES_DIR/shells/fish/init.fish\"" >$DOTFILES_CONF
end

function install_fisher_plugins
    # Install Fisher plugins
    if test -f "$DOTFILES_DIR/shells/fish/fish_plugins"
        echo "Installing Fisher plugins from $DOTFILES_DIR/shells/fish/fish_plugins"
        fish -c "fisher update"

        echo ""
        # Display Fisher plugin management instructions
        echo "✅ Fisher plugins installed. You can manage plugins with these commands:"
        echo "    fisher list                   # To list plugins"
        echo "    fisher update                 # To update plugins"
        echo "    fisher add <plugin-url>       # To add a plugin"
        echo "    fisher remove <plugin-name>   # To remove a plugin"
        echo ""
        echo "  Or edit $DOTFILES_DIR/shells/fish/fish_plugins and run 'fisher update'"
    else
        echo "warn: Fisher plugins file not found at $DOTFILES_DIR/shells/fish/fish_plugins, skipping installation"
    end
end

function install_dotfiles_success
    echo ""
    echo "✅ Fish shell configuration completed. If you want to make fish your default shell, run:"
    echo "    chsh -s (which fish)"
end

install_dotfiles_conf
install_fisher_plugins
install_dotfiles_success
