# Set default editor in Fish shell

# Try to load the $DOTFILES_DIR/local/editor.env.sh generated by dot.yaml install
if test -f $DOTFILES_DIR/local/editor.env.sh
    source $DOTFILES_DIR/local/editor.env.sh
end

# fallback - respect any existing values or use defaults
set -q __dotfiles_editor_opts; or set -gx __dotfiles_editor_opts "nvim vim nano vi"
set -q __dotfiles_visual_opts; or set -gx __dotfiles_visual_opts "cursor code zed nvim vim nano vi"

# Function to find first available command from a list of options
function find_first_available_cmd
    set options (string split " " $argv[1])
    for cmd in $options
        if command -v $cmd >/dev/null 2>&1
            echo $cmd
            return 0
        end
    end
    return 1
end

# Set EDITOR and VISUAL to first available editor
set -gx EDITOR (find_first_available_cmd "$__dotfiles_editor_opts")
set -gx VISUAL (find_first_available_cmd "$__dotfiles_visual_opts")
