[custom.fishcognito]
command = """ printf ' \\xF0\\x9F\\x91\\xBB' """
when = """ test "$fishcognito_active" = "true" """
# https://starship.rs/migrating-to-0.45.0/
# prefix = ""
format = ""

# [character]
# symbol = "➜"
# error_symbol = "✗"
# use_symbol_for_status = true

[directory]
truncate_to_repo = false

[kubernetes]
# disabled = false
