ln -fs ~/dotfiles/home/.npmignore ~/
ln -fs ~/dotfiles/home/.envrc ~/
ln -fs ~/dotfiles/home/.vim ~/
ln -fs ~/dotfiles/home/.tmux.conf ~/
ln -fs ~/dotfiles/home/.bash_profile ~/
ln -fs ~/dotfiles/home/.bashrc ~/
ln -fs ~/dotfiles/home/.zshrc ~/
ln -fs ~/dotfiles/home/.ackrc ~/
ln -fs ~/dotfiles/home/.editorconfig ~/
ln -fs ~/dotfiles/home/.vimrc ~/
ln -fs ~/dotfiles/home/.profile ~/
ln -fs ~/dotfiles/home/.asdfrc ~/
ln -fs ~/dotfiles/.config/omf ~/.config/
ln -fs ~/dotfiles/.config/nvim ~/.config/
ln -fs ~/dotfiles/.config/starship.toml ~/.config/
ln -fs ~/dotfiles/.config/direnv ~/.config/
ln -fs ~/dotfiles/.config/fish ~/.config/
ln -fs ~/dotfiles/.config/git ~/.config/
