#!/usr/bin/env bash
set -e

# Dotfiles Installer
# This script installs and configures the dotfiles
# It can be run multiple times safely (idempotent)

# Colors and formatting
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
RESET='\033[0m'

# Default settings
DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SHELL_TYPE="auto"  # Can be "fish", "zsh", or "auto"
INSTALL_MODE="full"  # Can be "minimal", "full", or "interactive"
DRY_RUN=false
BACKUP=true
VERBOSE=false

# Usage information
usage() {
  cat <<EOF
Usage: $(basename "$0") [options]

Options:
  --shell=TYPE       Select shell type (fish, zsh, auto)
  --minimal          Perform minimal installation
  --full             Perform full installation (default)
  --interactive      Interactive installation with prompts
  --dry-run          Show what would be done without making changes
  --no-backup        Don't backup existing files
  --verbose          Show more detailed output
  -h, --help         Show this help message

Examples:
  $(basename "$0") --shell=fish       # Install with fish shell
  $(basename "$0") --minimal          # Minimal installation
  $(basename "$0") --interactive      # Interactive installation
EOF
  exit 0
}

# Log messages with colors
log() {
  local level="$1"
  local message="$2"
  local color=""

  case "$level" in
    info) color="$BLUE" ;;
    success) color="$GREEN" ;;
    warning) color="$YELLOW" ;;
    error) color="$RED" ;;
    *) color="$RESET" ;;
  esac

  printf "${color}${BOLD}[$(basename "$0")]${RESET} ${color}%s${RESET}\n" "$message"
}

# Execute or print a command
execute() {
  local cmd="$*"

  if [ "$VERBOSE" = true ]; then
    log "info" "Executing: $cmd"
  fi

  if [ "$DRY_RUN" = true ]; then
    log "info" "Would execute: $cmd"
    return 0
  fi

  eval "$cmd"
  return $?
}

# Backup a file
backup_file() {
  local file="$1"
  local backup="${file}.bak.$(date +%Y%m%d%H%M%S)"

  if [ "$BACKUP" = false ] || [ ! -e "$file" ]; then
    return 0
  fi

  log "info" "Backing up ${file} to ${backup}"

  if [ "$DRY_RUN" = false ]; then
    execute "cp -R \"$file\" \"$backup\""
  fi
}

# Create a minimal shell config that sources from dotfiles
create_shell_stub() {
  local shell_type="$1"
  local target_file="$2"
  local content="$3"

  if [ -f "$target_file" ]; then
    backup_file "$target_file"
  fi

  log "info" "Creating $shell_type stub at $target_file"

  if [ "$DRY_RUN" = false ]; then
    mkdir -p "$(dirname "$target_file")"
    echo "$content" > "$target_file"
    log "success" "Created $shell_type configuration at $target_file"
    log "info" "You can add your own customizations directly to this file after the generated section"
  fi
}

# Parse command line arguments
parse_args() {
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --shell=*)
        SHELL_TYPE="${1#*=}"
        ;;
      --minimal)
        INSTALL_MODE="minimal"
        ;;
      --full)
        INSTALL_MODE="full"
        ;;
      --interactive)
        INSTALL_MODE="interactive"
        ;;
      --dry-run)
        DRY_RUN=true
        ;;
      --no-backup)
        BACKUP=false
        ;;
      --verbose)
        VERBOSE=true
        ;;
      -h|--help)
        usage
        ;;
      *)
        log "error" "Unknown option: $1"
        usage
        ;;
    esac
    shift
  done
}

# Detect the current shell
detect_shell() {
  if [ "$SHELL_TYPE" != "auto" ]; then
    return
  fi

  if [[ "$SHELL" == *fish* ]]; then
    SHELL_TYPE="fish"
  elif [[ "$SHELL" == *zsh* ]]; then
    SHELL_TYPE="zsh"
  else
    SHELL_TYPE="zsh"  # Default to zsh if detection fails
  fi

  log "info" "Auto-detected shell: $SHELL_TYPE"
}

# Install shell stubs
install_shell_stubs() {
  log "info" "Installing shell configuration stubs"

  # Fish shell stub
  if [ "$SHELL_TYPE" = "fish" ] || [ "$INSTALL_MODE" = "full" ]; then
    local fish_config_dir="$HOME/.config/fish"
    local fish_config="$fish_config_dir/config.fish"
    local fish_stub_content="# Generated by dotfiles installer
# Source dotfiles repository
set -gx DOTFILES_DIR \"$DOTFILES_DIR\"
if not test -e \$DOTFILES_DIR/shells/fish/config.fish
  echo \"Error: Could not find \$DOTFILES_DIR/shells/fish/config.fish\"
  exit 1
end
source \$DOTFILES_DIR/shells/fish/config.fish

# Add your machine-specific customizations below this line
# They will not be overwritten when updating the dotfiles repo
"

    create_shell_stub "fish" "$fish_config" "$fish_stub_content"

    # Only link Fisher plugins file here if it exists
    # (Full linking and installation happens later in the script)
    if [ -f "$DOTFILES_DIR/shells/fish/fish_plugins" ]; then
      log "info" "Found Fisher plugins file"
    else
      log "warning" "Fisher plugins file not found at $DOTFILES_DIR/shells/fish/fish_plugins"
    fi
  fi

  # ZSH shell stub
  if [ "$SHELL_TYPE" = "zsh" ] || [ "$INSTALL_MODE" = "full" ]; then
    local zsh_config="$HOME/.zshrc"
    local zsh_stub_content="# Generated by dotfiles installer
# Source dotfiles repository
export DOTFILES_DIR=\"$DOTFILES_DIR\"
if [ ! -f \"\$DOTFILES_DIR/shells/zsh/.zshrc\" ]; then
  echo \"Error: Could not find \$DOTFILES_DIR/shells/zsh/.zshrc\"
  exit 1
fi
source \$DOTFILES_DIR/shells/zsh/.zshrc

# Add your machine-specific customizations below this line
# They will not be overwritten when updating the dotfiles repo
"

    create_shell_stub "zsh" "$zsh_config" "$zsh_stub_content"

    # Check for Zsh plugins file
    if [ -f "$DOTFILES_DIR/shells/zsh/zsh_plugins" ]; then
      log "info" "Found Zsh plugins list file"
    else
      log "warning" "Zsh plugins list file not found at $DOTFILES_DIR/shells/zsh/zsh_plugins"
    fi
  fi
}



# Create basic aliases
create_basic_aliases() {
  log "info" "Creating basic aliases"

  execute "mkdir -p \"$DOTFILES_DIR/core/aliases.d\""

  # Create fish aliases
  if [ ! -f "$DOTFILES_DIR/core/aliases.d/common.fish" ] && ([ "$SHELL_TYPE" = "fish" ] || [ "$INSTALL_MODE" = "full" ]); then
    local fish_aliases_content="# Common aliases for fish shell

alias l='ls -la'
alias ..='cd ..'
alias ...='cd ../..'
"

    if [ "$DRY_RUN" = false ]; then
      echo "$fish_aliases_content" > "$DOTFILES_DIR/core/aliases.d/common.fish"
    fi
  fi

  # Create bash/zsh aliases
  if [ ! -f "$DOTFILES_DIR/core/aliases.d/common.sh" ] && ([ "$SHELL_TYPE" = "zsh" ] || [ "$INSTALL_MODE" = "full" ]); then
    local sh_aliases_content="# Common aliases for bash/zsh shells

alias l='ls -la'
alias ..='cd ..'
alias ...='cd ../..'
"

    if [ "$DRY_RUN" = false ]; then
      echo "$sh_aliases_content" > "$DOTFILES_DIR/core/aliases.d/common.sh"
    fi
  fi
}

# Install Fisher plugin manager for Fish shell
install_fisher() {
  if ! command -v fish &> /dev/null; then
    log "warning" "Fish shell is not installed. Skipping Fisher installation."
    return 1
  fi

  log "info" "Checking for Fisher plugin manager..."

  # Check if Fisher is already installed
  if fish -c "functions -q fisher" &> /dev/null; then
    log "info" "Fisher is already installed"
    return 0
  fi

  log "info" "Installing Fisher plugin manager..."

  # Create fish config directory if it doesn't exist
  mkdir -p "$HOME/.config/fish"

  # Install Fisher
  if [ "$DRY_RUN" = true ]; then
    log "info" "Would install Fisher with: curl -sL https://git.io/fisher | fish"
  else
    curl -sL https://git.io/fisher | fish

    # Verify installation
    if ! fish -c "functions -q fisher" &> /dev/null; then
      log "warning" "Fisher installation might have failed. Please install it manually after setup."
      return 1
    fi

    log "success" "Fisher installed successfully!"
  fi

  return 0
}

# Install Zinit (lightweight plugin manager for Zsh)
install_zinit() {
  if ! command -v zsh &> /dev/null; then
    log "warning" "Zsh shell is not installed. Skipping Zinit installation."
    return 1
  fi

  log "info" "Checking for Zinit..."

  # Set Zinit home directory
  ZINIT_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/zinit/zinit.git"

  # Check if Zinit is already installed
  if [ -d "$ZINIT_HOME" ]; then
    log "info" "Zinit is already installed"
    return 0
  fi

  log "info" "Installing Zinit plugin manager..."

  # Install Zinit
  if [ "$DRY_RUN" = true ]; then
    log "info" "Would install Zinit with: mkdir -p \"$(dirname $ZINIT_HOME)\" && git clone https://github.com/zdharma-continuum/zinit.git \"$ZINIT_HOME\""
  else
    # Create parent directory and clone Zinit
    mkdir -p "$(dirname $ZINIT_HOME)"
    git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"

    # Verify installation
    if [ ! -d "$ZINIT_HOME" ]; then
      log "warning" "Zinit installation might have failed. Please install it manually after setup."
      return 1
    fi

    log "success" "Zinit installed successfully!"
  fi

  return 0
}

# No separate install_zsh_plugins function needed as Zinit handles plugin installation when sourced

# Main installation function
install_dotfiles() {
  log "info" "Starting dotfiles installation (mode: $INSTALL_MODE, shell: $SHELL_TYPE)"

  # Check that required shell configuration files exist
  if [ "$SHELL_TYPE" = "fish" ] || [ "$INSTALL_MODE" = "full" ]; then
    if [ ! -f "$DOTFILES_DIR/shells/fish/config.fish" ]; then
      log "error" "Required file not found: $DOTFILES_DIR/shells/fish/config.fish"
      log "error" "Please ensure the dotfiles repository is correctly cloned."
      exit 1
    fi

    # Check for Fish plugins list
    if [ ! -f "$DOTFILES_DIR/shells/fish/fish_plugins" ]; then
      log "warning" "Fish plugins list not found: $DOTFILES_DIR/shells/fish/fish_plugins"
      log "info" "You may want to create this file to manage your Fisher plugins."
    else
      log "info" "Found Fish plugins list"
    fi
  fi

  if [ "$SHELL_TYPE" = "zsh" ] || [ "$INSTALL_MODE" = "full" ]; then
    if [ ! -f "$DOTFILES_DIR/shells/zsh/.zshrc" ]; then
      log "error" "Required file not found: $DOTFILES_DIR/shells/zsh/.zshrc"
      log "error" "Please ensure the dotfiles repository is correctly cloned."
      exit 1
    fi

    # Check for Zsh plugins list
    if [ ! -f "$DOTFILES_DIR/shells/zsh/zsh_plugins" ]; then
      log "warning" "Zsh plugins list not found: $DOTFILES_DIR/shells/zsh/zsh_plugins"
      log "info" "You may want to create this file to manage your Zsh plugins."
    else
      log "info" "Found Zsh plugins list"
    fi
  fi

  # Create core directory structure if needed
  execute "mkdir -p \"$DOTFILES_DIR/core/aliases.d\""
  execute "mkdir -p \"$DOTFILES_DIR/core/env.d\""
  execute "mkdir -p \"$DOTFILES_DIR/core/functions.d\""
  execute "mkdir -p \"$DOTFILES_DIR/core/paths.d\""

  # Create basic aliases
  create_basic_aliases

  # Install shell stubs
  install_shell_stubs

  # Install Fisher plugin manager for Fish
  if [ "$SHELL_TYPE" = "fish" ] || [ "$INSTALL_MODE" = "full" ]; then
    if [ -f "$DOTFILES_DIR/shells/fish/fish_plugins" ]; then
      # Link fisher plugins file before installing Fisher
      log "info" "Linking fish_plugins file from dotfiles repository..."
      mkdir -p "$HOME/.config/fish"
      ln -sf "$DOTFILES_DIR/shells/fish/fish_plugins" "$HOME/.config/fish/fish_plugins"

      # Install Fisher
      install_fisher

      # Install plugins with Fisher if it was installed successfully
      if [ $? -eq 0 ] && [ "$DRY_RUN" = false ]; then
        log "info" "Installing plugins from fish_plugins list..."
        fish -c "fisher update"
        log "success" "Plugins installed successfully!"
      fi
    fi
  fi

  # Install Zinit for Zsh
  if [ "$SHELL_TYPE" = "zsh" ] || [ "$INSTALL_MODE" = "full" ]; then
    if [ -f "$DOTFILES_DIR/shells/zsh/zsh_plugins" ]; then
      # Install Zinit
      install_zinit

      # Plugins will be loaded automatically from zsh_plugins file when zsh starts
      if [ $? -eq 0 ] && [ "$DRY_RUN" = false ]; then
        log "info" "Plugins defined in zsh_plugins will be loaded when you start Zsh"
      fi
    fi
  fi

  # Additional setup based on installation mode
  if [ "$INSTALL_MODE" = "full" ] || [ "$INSTALL_MODE" = "interactive" ]; then
    log "info" "Performing full installation"
    # Additional full installation steps would go here
  fi

  log "success" "Dotfiles installation completed successfully!"

  # Fish plugin management instructions
  if [ "$SHELL_TYPE" = "fish" ] || [ "$INSTALL_MODE" = "full" ]; then
    if [ -f "$DOTFILES_DIR/shells/fish/fish_plugins" ]; then
      if fish -c "functions -q fisher" &> /dev/null; then
        log "info" "Fisher is installed. You can manage plugins with these commands:"
        log "info" "- To list plugins:   fisher list"
        log "info" "- To update plugins: fisher update"
        log "info" "- To add a plugin:   fisher add <plugin-url>"
        log "info" "- To remove a plugin: fisher remove <plugin-name>"
        log "info" "- Or edit $DOTFILES_DIR/shells/fish/fish_plugins and run 'fisher update'"
      else
        log "warning" "Fisher was not installed. To install it manually, run:"
        log "info" "curl -sL https://git.io/fisher | fish"
      fi
    fi
  fi

  # Zsh plugin management instructions
  if [ "$SHELL_TYPE" = "zsh" ] || [ "$INSTALL_MODE" = "full" ]; then
    if [ -f "$DOTFILES_DIR/shells/zsh/zsh_plugins" ]; then
      ZINIT_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/zinit/zinit.git"
      if [ -d "$ZINIT_HOME" ]; then
        log "info" "Zinit is installed. You can manage plugins with these commands:"
        log "info" "- Edit plugins in $DOTFILES_DIR/shells/zsh/zsh_plugins"
        log "info" "- To update plugins: zinit update --all"
        log "info" "- To add a plugin: add 'zinit light author/repo' to zsh_plugins"
      else
        log "warning" "Zinit was not installed. To install it manually, run:"
        log "info" "mkdir -p \"${XDG_DATA_HOME:-$HOME/.local/share}/zinit\" && \\"
        log "info" "git clone https://github.com/zdharma-continuum/zinit.git \"${XDG_DATA_HOME:-$HOME/.local/share}/zinit/zinit.git\""
      fi
    fi
  fi

  if [ "$SHELL_TYPE" = "fish" ]; then
    log "info" "To apply changes, restart your terminal or run: source ~/.config/fish/config.fish"
  else
    log "info" "To apply changes, restart your terminal or run: source ~/.zshrc"
  fi
}

# Main execution
main() {
  parse_args "$@"
  detect_shell
  install_dotfiles
}

main "$@"
