#!/usr/bin/env bash
set -e

# Dotfiles Installer
# This script installs and configures the dotfiles
# It can be run multiple times safely (idempotent)

# Colors and formatting
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
RESET='\033[0m'

# Default settings
DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SHELL_TYPE="auto"  # Can be "fish", "zsh", or "auto"
INSTALL_MODE="full"  # Can be "minimal", "full", or "interactive"
DRY_RUN=false
BACKUP=true
VERBOSE=false

# Usage information
usage() {
  cat <<EOF
Usage: $(basename "$0") [options]

Options:
  --shell=TYPE       Select shell type (fish, zsh, auto)
  --minimal          Perform minimal installation
  --full             Perform full installation (default)
  --interactive      Interactive installation with prompts
  --dry-run          Show what would be done without making changes
  --no-backup        Don't backup existing files
  --verbose          Show more detailed output
  -h, --help         Show this help message

Examples:
  $(basename "$0") --shell=fish       # Install with fish shell
  $(basename "$0") --minimal          # Minimal installation
  $(basename "$0") --interactive      # Interactive installation
EOF
  exit 0
}

# Log messages with colors
log() {
  local level="$1"
  local message="$2"
  local color=""

  case "$level" in
    info) color="$BLUE" ;;
    success) color="$GREEN" ;;
    warning) color="$YELLOW" ;;
    error) color="$RED" ;;
    *) color="$RESET" ;;
  esac

  printf "${color}${BOLD}[$(basename "$0")]${RESET} ${color}%s${RESET}\n" "$message"
}

# Execute or print a command
execute() {
  local cmd="$*"

  if [ "$VERBOSE" = true ]; then
    log "info" "Executing: $cmd"
  fi

  if [ "$DRY_RUN" = true ]; then
    log "info" "Would execute: $cmd"
    return 0
  fi

  eval "$cmd"
  return $?
}

# Backup a file
backup_file() {
  local file="$1"
  local backup="${file}.bak.$(date +%Y%m%d%H%M%S)"

  if [ "$BACKUP" = false ] || [ ! -e "$file" ]; then
    return 0
  fi

  log "info" "Backing up ${file} to ${backup}"

  if [ "$DRY_RUN" = false ]; then
    execute "cp -R \"$file\" \"$backup\""
  fi
}

# Create a minimal shell config that sources from dotfiles
create_shell_stub() {
  local shell_type="$1"
  local target_file="$2"
  local content="$3"

  if [ -f "$target_file" ]; then
    backup_file "$target_file"
  fi

  log "info" "Creating $shell_type stub at $target_file"

  if [ "$DRY_RUN" = false ]; then
    mkdir -p "$(dirname "$target_file")"
    echo "$content" > "$target_file"
    log "success" "Created $shell_type configuration at $target_file"
    log "info" "You can add your own customizations directly to this file after the generated section"
  fi
}

# Parse command line arguments
parse_args() {
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --shell=*)
        SHELL_TYPE="${1#*=}"
        ;;
      --minimal)
        INSTALL_MODE="minimal"
        ;;
      --full)
        INSTALL_MODE="full"
        ;;
      --interactive)
        INSTALL_MODE="interactive"
        ;;
      --dry-run)
        DRY_RUN=true
        ;;
      --no-backup)
        BACKUP=false
        ;;
      --verbose)
        VERBOSE=true
        ;;
      -h|--help)
        usage
        ;;
      *)
        log "error" "Unknown option: $1"
        usage
        ;;
    esac
    shift
  done
}

# Detect the current shell
detect_shell() {
  if [ "$SHELL_TYPE" != "auto" ]; then
    return
  fi

  if [[ "$SHELL" == *fish* ]]; then
    SHELL_TYPE="fish"
  elif [[ "$SHELL" == *zsh* ]]; then
    SHELL_TYPE="zsh"
  else
    SHELL_TYPE="zsh"  # Default to zsh if detection fails
  fi

  log "info" "Auto-detected shell: $SHELL_TYPE"
}

# Install basic shell stubs
install_shell_stubs() {
  log "info" "Installing shell configuration stubs"

  # Fish shell stub
  if [ "$SHELL_TYPE" = "fish" ] || [ "$INSTALL_MODE" = "full" ]; then
    local fish_config_dir="$HOME/.config/fish"
    local fish_config="$fish_config_dir/config.fish"
    local fish_stub_content="# Generated by dotfiles installer
# Source dotfiles repository
set -gx DOTFILES_DIR \"$DOTFILES_DIR\"
if not test -e \$DOTFILES_DIR/shells/fish/config.fish
  echo \"Error: Could not find \$DOTFILES_DIR/shells/fish/config.fish\"
  exit 1
end
source \$DOTFILES_DIR/shells/fish/config.fish

# Add your machine-specific customizations below this line
# They will not be overwritten when updating the dotfiles repo
"

    create_shell_stub "fish" "$fish_config" "$fish_stub_content"
  fi

  # ZSH shell stub
  if [ "$SHELL_TYPE" = "zsh" ] || [ "$INSTALL_MODE" = "full" ]; then
    local zsh_config="$HOME/.zshrc"
    local zsh_stub_content="# Generated by dotfiles installer
# Source dotfiles repository
export DOTFILES_DIR=\"$DOTFILES_DIR\"
if [ ! -f \"\$DOTFILES_DIR/shells/zsh/.zshrc\" ]; then
  echo \"Error: Could not find \$DOTFILES_DIR/shells/zsh/.zshrc\"
  exit 1
fi
source \$DOTFILES_DIR/shells/zsh/.zshrc

# Add your machine-specific customizations below this line
# They will not be overwritten when updating the dotfiles repo
"

    create_shell_stub "zsh" "$zsh_config" "$zsh_stub_content"
  fi
}



# Create basic aliases
create_basic_aliases() {
  log "info" "Creating basic aliases"

  execute "mkdir -p \"$DOTFILES_DIR/core/aliases.d\""

  # Create fish aliases
  if [ ! -f "$DOTFILES_DIR/core/aliases.d/common.fish" ] && ([ "$SHELL_TYPE" = "fish" ] || [ "$INSTALL_MODE" = "full" ]); then
    local fish_aliases_content="# Common aliases for fish shell

alias l='ls -la'
alias ..='cd ..'
alias ...='cd ../..'
"

    if [ "$DRY_RUN" = false ]; then
      echo "$fish_aliases_content" > "$DOTFILES_DIR/core/aliases.d/common.fish"
    fi
  fi

  # Create bash/zsh aliases
  if [ ! -f "$DOTFILES_DIR/core/aliases.d/common.sh" ] && ([ "$SHELL_TYPE" = "zsh" ] || [ "$INSTALL_MODE" = "full" ]); then
    local sh_aliases_content="# Common aliases for bash/zsh shells

alias l='ls -la'
alias ..='cd ..'
alias ...='cd ../..'
"

    if [ "$DRY_RUN" = false ]; then
      echo "$sh_aliases_content" > "$DOTFILES_DIR/core/aliases.d/common.sh"
    fi
  fi
}

# Main installation function
install_dotfiles() {
  log "info" "Starting dotfiles installation (mode: $INSTALL_MODE, shell: $SHELL_TYPE)"

  # Check that required shell configuration files exist
  if [ "$SHELL_TYPE" = "fish" ] || [ "$INSTALL_MODE" = "full" ]; then
    if [ ! -f "$DOTFILES_DIR/shells/fish/config.fish" ]; then
      log "error" "Required file not found: $DOTFILES_DIR/shells/fish/config.fish"
      log "error" "Please ensure the dotfiles repository is correctly cloned."
      exit 1
    fi
  fi

  if [ "$SHELL_TYPE" = "zsh" ] || [ "$INSTALL_MODE" = "full" ]; then
    if [ ! -f "$DOTFILES_DIR/shells/zsh/.zshrc" ]; then
      log "error" "Required file not found: $DOTFILES_DIR/shells/zsh/.zshrc"
      log "error" "Please ensure the dotfiles repository is correctly cloned."
      exit 1
    fi
  fi

  # TODO: why do we need to create these folders during installation?
  # Create core directory structure if needed
  execute "mkdir -p \"$DOTFILES_DIR/core/aliases.d\""
  execute "mkdir -p \"$DOTFILES_DIR/core/env.d\""
  execute "mkdir -p \"$DOTFILES_DIR/core/functions.d\""
  execute "mkdir -p \"$DOTFILES_DIR/core/paths.d\""
  execute "mkdir -p \"$DOTFILES_DIR/core/plugins.d\""

  # Create basic aliases
  create_basic_aliases

  # Install shell stubs
  install_shell_stubs

  # Additional setup based on installation mode
  if [ "$INSTALL_MODE" = "full" ] || [ "$INSTALL_MODE" = "interactive" ]; then
    log "info" "Performing full installation"
    # Additional setup would go here
  fi

  log "success" "Dotfiles installation completed successfully!"

  if [ "$SHELL_TYPE" = "fish" ]; then
    log "info" "To apply changes, restart your terminal or run: source ~/.config/fish/config.fish"
  else
    log "info" "To apply changes, restart your terminal or run: source ~/.zshrc"
  fi
}

# Main execution
main() {
  parse_args "$@"
  detect_shell
  install_dotfiles
}

main "$@"
